/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Events, EventsInterface } from "../Events";

const _abi = [
  {
    type: "event",
    name: "BuyCreditLimit",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "maxDueDate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "curveRelativeTimeTenors",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "curveRelativeTimeAprs",
        type: "int256[]",
        indexed: false,
        internalType: "int256[]",
      },
      {
        name: "curveRelativeTimeMarketRateMultipliers",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BuyCreditMarket",
    inputs: [
      {
        name: "lender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creditPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tenor",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "minAPR",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "exactAmountIn",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Claim",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creditPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Compensate",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creditPositionWithDebtToRepayId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creditPositionToCompensateId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CopyLimitOrders",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "copyAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "minTenorLoanOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxTenorLoanOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "minAPRLoanOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxAPRLoanOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "offsetAPRLoanOffer",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
      {
        name: "minTenorBorrowOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxTenorBorrowOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "minAPRBorrowOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxAPRBorrowOffer",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "offsetAPRBorrowOffer",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreateCreditPosition",
    inputs: [
      {
        name: "creditPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "lender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "debtPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "exitPositionId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "credit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "forSale",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreateDebtPosition",
    inputs: [
      {
        name: "debtPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "lender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "futureValue",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "dueDate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposit",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialize",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Liquidate",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "debtPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "minimumCollateralProfit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "collateralRatio",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "loanStatus",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LiquidateWithReplacement",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "debtPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "minimumCollateralProfit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "minAPR",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Repay",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "debtPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SelfLiquidate",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creditPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SellCreditLimit",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "maxDueDate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "curveRelativeTimeTenors",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "curveRelativeTimeAprs",
        type: "int256[]",
        indexed: false,
        internalType: "int256[]",
      },
      {
        name: "curveRelativeTimeMarketRateMultipliers",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SellCreditMarket",
    inputs: [
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "lender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creditPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tenor",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxAPR",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "exactAmountIn",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetUserConfiguration",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "openingLimitBorrowCR",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "allCreditPositionsForSaleDisabled",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "creditPositionIdsForSale",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "creditPositionIds",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SwapData",
    inputs: [
      {
        name: "creditPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "lender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "credit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cashIn",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cashOut",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "swapFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "fragmentationFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tenor",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateConfig",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "key",
        type: "string",
        indexed: true,
        internalType: "string",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateCreditPosition",
    inputs: [
      {
        name: "creditPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "lender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "credit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "forSale",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateDebtPosition",
    inputs: [
      {
        name: "debtPositionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "futureValue",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "liquidityIndexAtRepayment",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VariablePoolBorrowRateUpdated",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "oldBorrowRate",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "newBorrowRate",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdraw",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

const _bytecode =
  "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122078cdd70420a1846220d4e18b0a863ea7445dff571407b648fb7fe7c85ba31e6964736f6c63430008170033";

type EventsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EventsConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Events__factory extends ContractFactory {
  constructor(...args: EventsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string },
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Events & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Events__factory {
    return super.connect(runner) as Events__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EventsInterface {
    return new Interface(_abi) as EventsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Events {
    return new Contract(address, _abi, runner) as unknown as Events;
  }
}
